---
#task file for db setup
    - name: Delete data directory if exists
      command: rm -rf /var/lib/pgsql/9.5/data/

    - name: Init db
      command: '/usr/pgsql-9.5/bin/postgresql95-setup initdb'
      ignore_errors: yes

    - name: Change permission of /var/lib/pgsql/9.5/data
      file:
        path: /var/lib/pgsql/9.5/data
        owner: 26
        group: 26
        mode: 0700   
    
    - name: Create pg_hba.conf file
      copy:
        content: | 
          # TYPE  DATABASE        USER            ADDRESS                 METHOD

          # "local" is for Unix domain socket connections only
          local   all             all                                     peer
          # IPv4 local connections:
          #host    all             all             127.0.0.1/32            ident
          host    all             all             127.0.0.1/32            md5
          # IPv6 local connections:
          #host    all             all             ::1/128                 ident
          host    all             all             ::1/128                 md5      
        dest: /var/lib/pgsql/9.5/data/pg_hba.conf 

    - name: Start postgresql-9.5 service 
      service: 
        name: postgresql-9.5
        enabled: yes
        state: started

    - name: Alter db user password
      command: sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"

    - name: Creeate database
      command: sudo -u postgres psql -c "CREATE DATABASE transtats"
   
